[ci] Add testing to the correct job

diff --git a/.git-ci/gitlab-iem.yml b/.git-ci/gitlab-iem.yml
--- a/.git-ci/gitlab-iem.yml
+++ b/.git-ci/gitlab-iem.yml
@@ -73,6 +73,37 @@ stages:
     - mkdir Standalone
     - find build/*/*_artefacts/Standalone/ -maxdepth 1 -type f -executable -not -name "*.so" -exec cp {} Standalone/ ";"
 
+    # TODO: This is only here for debugging the ci
+    - curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_Linux.zip" -o pluginval.zip
+    - unzip pluginval
+    - rm -f failed-tests.txt
+    - rm -rf test-logs
+    - mkdir test-logs
+
+    - |
+      find VST/ -name "*.so" | while read fname; do
+        logfile="test-logs/${fname##*/}.txt"
+        ./pluginval --validate-in-process --strictness-level 10 --repeat 1 --skip-gui-tests "$fname" | tee ${logfile} || echo "${fname} failed with exit code $?" >> failed-tests.txt;
+      done
+
+    - |
+      find VST3/ -name "*.vst3" | while read fname; do
+        logfile="test-logs/${fname##*/}.txt"
+        ./pluginval --validate-in-process --strictness-level 10 --repeat 1 --skip-gui-tests "$fname" | tee ${logfile} || echo "${fname} failed with exit code $?" >> failed-tests.txt;
+      done
+
+    - |
+      if test -f failed-tests.txt; then
+          echo "Some tests failed, check artifacts for details..."
+          exit 1
+      fi
+
+  artifacts:
+    when: on_failure
+    paths:
+      - failed-tests.txt
+      - test-logs
+
 .build:macos:
   stage: build
   tags:
@@ -117,37 +148,6 @@ stages:
     - mkdir Standalone
     - cp -r build/*/*_artefacts/Release/Standalone/*.app Standalone/
 
-
-## TODO: The rest is basically only testing...
-    - curl -L "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_Linux.zip" -o pluginval.zip
-    - unzip pluginval
-    - rm -f failed-tests.txt
-    - rm -rf test-logs
-    - mkdir test-logs
-
-    - |
-      find VST/ -name "*.so" | while read fname; do
-        logfile="test-logs/${fname##*/}.txt"
-        ./pluginval --validate-in-process --strictness-level 10 --repeat 1 --skip-gui-tests "$fname" | tee ${logfile} || echo "${fname} failed with exit code $?" >> failed-tests.txt;
-      done
-
-    - |
-      find VST3/ -name "*.vst3" | while read fname; do
-        logfile="test-logs/${fname##*/}.txt"
-        ./pluginval --validate-in-process --strictness-level 10 --repeat 1 --skip-gui-tests "$fname" | tee ${logfile} || echo "${fname} failed with exit code $?" >> failed-tests.txt;
-      done
-
-    - |
-      if test -f failed-tests.txt; then
-          echo "Some tests failed, check artifacts for details..."
-          exit 1
-      fi
-
-  artifacts:
-    when: on_failure
-    paths:
-      - failed-tests.txt
-      - test-logs
 
 # FIXME: Fix toolchain for windows adn cmake
 .build:windows:
